config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords'
  }
  root 'home#index'
  resources :workshops, only: %i[index show]
  resources :bookings, only: %i[create] do
    get :booking_details, on: :member 
  end
  namespace :admin do 
    get 'dashboard' => 'dashboard#index'
  end
end

app/models/workshop.rb
class Workshop < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  has_many :bookings
  has_many :customers, through: :bookings 
  validates :name, :description, presence: true
  validates :start_date, :end_date, :start_time, :end_time, presence: true
  validates :total_sits, :remaining_sits, presence: true, numericality: true
  validates :end_date, comparison: { greater_than: :start_date,
  message: 'can not be before start date' }

  scope :upcoming_workshops, -> { where('start_date > ?', Date.today)}
  scope :past_workshops, -> { where('end_date < ?', Date.today)}
  
  def total_duration 
    "From #{start_date} to #{end_date}"
  end

  def daily_workshop_hours 
    "#{((start_time.to_time - end_time.to_time)/1.hours).abs} hours"
  end

  def daily_duration 
    "Everyday #{start_time} to #{end_time} (#{daily_workshop_hours})"
  end

  def is_upcoming_workshop?
    start_date > Date.today
  end

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController 
  def index 
    @workshops = Workshop.upcoming_workshops 
  end
  def show 
    @workshop = Workshop.friendly.find(params[:id])
  end
end

app/views/workshops/index.html.erb
<%= render 'shared/workshops', workshops: @workshops, section_title: 'Listing Workshops' %>

app/views/workshops/show.html.erb
<div class="col-lg-8 mt-4">
  <div class="card shadow mb-3">
    <div class="card-body">
      <h4 class="card-title"><%= @workshop.name %></h4>
      <div class="row mt-3">

        <div class="col-lg-7">
          <h4> <span class="badge bg-primary"> <%= @workshop.total_duration%> </h4>
          <h4> <span class="badge bg-primary"> <%= @workshop.daily_duration%> </h4>
        </div>
        <div class="col-lg-5">
          <h4> Total Sits:<span class="badge bg-primary"><%= @workshop.total_sits%> </span></h4>
          <h4> Remaining Sits:<span class="badge bg-primary"><%= @workshop.remaining_sits%> </span></h4>
          <h4> Registration Fee:<span class="badge bg-primary"><%= @workshop.registration_fee%> </span></h4>
        </div>
      </div>
      <p class="lead mt-3 mb-3"><%= @workshop.description%> </p>
        <%= link_to 'Back to Workshops', workshops_path, class:"btn btn-outline-danger mt-3"%>
    </div>
  </div>
</div>
<div class="col-lg-4 mt-4">
  <div class="card shadow mb-3">
    <div class="card-body">
    <% if @workshop.is_upcoming_workshop? %>
      <h4 class="card-title mb-2">Reserve your sit now!</h4>
      <%= form_with url: :bookings, data: {turbo: false} do |form| %>
        <%= form.hidden_field :workshop_id, value: @workshop.id %>
        <div class="form-group">
          <%= form.label :full_name, class: "mb-2 mt-2" %>
          <%= form.text_field :full_name, class: "form-control", required:true %>
        </div>

        <div class="form-group">
          <%= form.label :email, class: "mb-2 mt-2" %>
          <%= form.email_field :email, class: "form-control", required:true %>
        </div>
        
        <div class="form-group">
          <%= form.label :contact_number, class: "mb-2 mt-2" %>
          <%= form.text_field :contact_number, class: "form-control", required:true %>
        </div>

        <div class="form-group">
          <%= form.label :no_of_sits_you_want_to_book, class: "mb-2 mt-2" %>
          <%= form.number_field :no_of_tickets, class: "form-control", required:true, min: 1, max:@workshop.remaining_sits %>
        </div>
        <h4 class="mt-4 mb-3">Card Details </h4>
        <hr>

        <div class="form-group">
          <%= form.label :card_number, class: "mb-2 mt-2" %>
          <%= form.text_field :card_number, class: "form-control", required:true %>
        </div>

        <div class="row">
          <div class="col-lg-6">
            <div class="form-group">
              <%= form.label :cvv, class: "mb-2 mt-2" %>
              <%= form.number_field :cvv, class: "form-control", required:true, maxlength:3 %>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="form-group">
              <%= form.label :month, class: "mb-2 mt-2" %>
              <%= form.number_field :exp_month, class: "form-control", required:true, min:1, max:12 %>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="form-group">
              <%= form.label :year, class: "mb-2 mt-2" %>
              <%= form.number_field :exp_year, class: "form-control", required:true, min:2022, max:2025 %>
            </div>
          </div>
        </div>

        <div class="d-grid gap-2">
          <%= form.submit "Book Your Tickets Now", class: "btn btn-outline-primary mt-3"%>
        </div>

      <% end %>
    <% else %>
      <h4 class="card-title mb-2">Workshop has already been taken!</h4>
    <% end %>
    </div>
  </div>
</div>