config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions',
    passwords: 'admin_users/passwords'
  }
  root 'home#index'
  resources :workshops, only: %i[index show]
  resources :bookings, only: %i[create] do
    get :booking_details, on: :member 
  end
  namespace :admin do 
    get 'dashboard' => 'dashboard#index'
  end
end

app/views/shared/_flash.html.erb
<div class="flash">
  <% flash.each do |key, value|%>
    <div class="<%= flash_class(key.to_sym)%> alert-dismissible fade show" role="alert">
      <% unless value == true %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= value%>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Webinar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if admin_user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_admin_user_session_path, method: :delete, class:"nav-link active"%>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Resources
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_workshops.html.erb
<h3 class="mt-4 mb-4"><%= section_title%></h3>
<div class="row">
  <% workshops.each do |workshop| %>
    <div class="col-lg-6">
      <div class="card shadow mb-3 mt-2">
        <div class="card-body">
          <h4 class="card-title"><%= workshop.name %> </h4>
          <p class="lead"> <%=workshop.description %></p>
          <h4> <span class="badge bg-primary"> <%= workshop.total_duration%> </h4>
          <h4> <span class="badge bg-primary"> <%= workshop.daily_duration%> </h4>
          <%= link_to 'View Details', workshop,  class:"btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
</div>